portal_servicos/gestao_barbearia/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'gestao_barbearia'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('funcionario/<int:funcionario_id>/agenda/', views.visualizar_agenda, name='visualizar_agenda'),
    path('barbearia/<int:barbearia_id>/acessar_cliente_app/', views.acessar_cliente_app, name='acessar_cliente_app'),
    path('funcionario/<int:funcionario_id>/agenda/', views.visualizar_agenda, name='visualizar_agenda'),

]

portal_servicos/portal/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

portal_servicos/portal_servicos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls')),
    path('gestao_barbearia/', include('gestao_barbearia.urls')),
    path('cliente_barbearia/', include('cliente_barbearia.urls')),
]

portal_servicos/gestao_barbearia/models.py
from django.db import models
from portal.models import Barbearia, CustomUser


class Funcionario(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    barbearia = models.ForeignKey(Barbearia, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username


class Funcao(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome
    
class Servico(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    duracao = models.DurationField()  # duração do serviço
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    funcao = models.ForeignKey(Funcao, on_delete=models.CASCADE)

    def __str__(self):
        # Converte a duração de timedelta para horas, minutos e segundos
        total_seconds = int(self.duracao.total_seconds())
        hours, remainder = divmod(total_seconds, 3600)
        minutes, seconds = divmod(remainder, 60)
        
        # Formata a duração como HH:MM:SS
        if hours == 0:
            duracao_formatada = f"{minutes:2}min"
        else:
            duracao_formatada = f"{hours:2}h {minutes:2}min"
        
        # Retorna o formato desejado
        return f"{self.nome} - {duracao_formatada}"

 
class Agendamento(models.Model):
    cliente = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='agendamentos')
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE, related_name='agendamentos')
    servico = models.ForeignKey(Servico, on_delete=models.CASCADE, related_name='servicos')
    data_hora = models.DateTimeField()

    class Meta:
        unique_together = ['funcionario', 'data_hora']

    def __str__(self):
        # Formata a data e hora para o formato desejado
        data_hora_formatada = self.data_hora.strftime('%d/%m/%Y %H:%M')
        return f"Cliente {self.cliente.username} - Barbeiro {self.funcionario.user.username} - agendado para {data_hora_formatada}"

    

portal_servicos/gestao_barbearia/forms.py
from django import forms
from portal.models import CustomUser
from .models import Funcionario, Funcao, Agendamento


class FuncionarioForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=CustomUser.objects.filter(is_staff=True))

    class Meta:
        model = Funcionario
        fields = ['user', 'barbearia']
        
class FuncionarioCreationForm(forms.ModelForm):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(required=False)
    funcao = forms.ModelChoiceField(queryset=Funcao.objects.all())

    class Meta:
        model = Funcionario
        fields = ['barbearia', 'funcao']

    def save(self, commit=True):
        user_data = {
            'username': self.cleaned_data['username'],
            'password': self.cleaned_data['password'],
            'first_name': self.cleaned_data.get('first_name', ''),
            'last_name': self.cleaned_data.get('last_name', ''),
            'email': self.cleaned_data.get('email', ''),
        }
        user = CustomUser.objects.create_user(**user_data)
        funcionario = super().save(commit=False)
        funcionario.user = user
        if commit:
            funcionario.save()
        return funcionario


class AgendamentoForm(forms.ModelForm):
    class Meta:
        model = Agendamento
        fields = ['servico', 'data_hora']

    def __init__(self, *args, **kwargs):
        self.funcionario = kwargs.pop('funcionario', None)
        super().__init__(*args, **kwargs)
        if self.funcionario:
            self.fields['servico'].queryset = self.funcionario.barbearia.servicos.all()

    def clean_data_hora(self):
        data_hora = self.cleaned_data['data_hora']
        duracao = self.cleaned_data['servico'].duracao
        conflito = Agendamento.objects.filter(
            funcionario=self.funcionario,
            data_hora__lt=data_hora + duracao,
            data_hora__gte=data_hora
        ).exists()
        if conflito:
            raise forms.ValidationError("Horário indisponível para agendamento.")
        return data_hora

portal_servicos/gestao_barbearia/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from portal.models import Barbearia
from .models import Funcionario, Agendamento, Servico, Funcao
from django.contrib.auth import logout


def logout_view(request):
    logout(request)
    return render(request, 'registration/login.html')

@login_required
def index(request):
    print("aqui 1")
    if request.user.is_owner_app:
        try:
            barbearia = Barbearia.objects.get(owner_app=request.user)
            funcionarios = Funcionario.objects.filter(barbearia=barbearia)
            for funcionario in funcionarios:
                funcoes = Funcao.objects.filter(funcionario=funcionario)
                for funcao in funcoes:
                    funcao.servicos = Servico.objects.filter(funcao=funcao)
                funcionario.funcoes = funcoes
        except Barbearia.DoesNotExist:
            barbearia = None
            funcionarios = []
        return render(request, 'gestao_barbearia/index.html', {'barbearia': barbearia, 'funcionarios': funcionarios, 'funcoes': funcoes})
    else:
        return render(request, 'gestao_barbearia/access_denied.html')


@login_required
def visualizar_agenda(request, funcionario_id):
    funcionario = get_object_or_404(Funcionario, id=funcionario_id)
    return render(request, 'gestao_barbearia/visualizar_agenda.html', {'funcionario': funcionario})

@login_required
def acessar_cliente_app(request, barbearia_id):
    barbearia = get_object_or_404(Barbearia, id=barbearia_id)
    if request.user.is_client_app and request.user.barbearias.filter(id=barbearia.id).exists():
        return redirect('cliente_barbearia:index')
    else:
        return redirect('cliente_barbearia:index')  # Redireciona diretamente para a página do cliente

@login_required
def visualizar_agenda(request, funcionario_id):
    funcionario = get_object_or_404(Funcionario, id=funcionario_id)
    agendamentos = funcionario.agendamentos.all().order_by('data_hora')
    return render(request, 'gestao_barbearia/visualizar_agenda.html', {'funcionario': funcionario, 'agendamentos': agendamentos})

portal_servicos/templates/gestao_barbearia/partials/_footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2020</span>
        </div>
    </div>
</footer>

portal_servicos/templates/gestao_barbearia/partials/_header.html
{% load static %}

<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 12, 2019</div>
                        <span class="font-weight-bold">A new monthly report is ready to download!</span>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 7, 2019</div>
                        $290.29 has been deposited into your account!
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-warning">
                            <i class="fas fa-exclamation-triangle text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 2, 2019</div>
                        Spending Alert: We've noticed unusually high spending for your account.
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src={% static "img/undraw_profile_1.svg" %}
                            alt="...">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">Hi there! I am wondering if you can help me with a
                            problem I've been having.</div>
                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src={% static "img/undraw_profile_2.svg" %}
                            alt="...">
                        <div class="status-indicator"></div>
                    </div>
                    <div>
                        <div class="text-truncate">I have the photos that you ordered last month, how
                            would you like them sent to you?</div>
                        <div class="small text-gray-500">Jae Chun · 1d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src={% static "img/undraw_profile_3.svg" %}
                            alt="...">
                        <div class="status-indicator bg-warning"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Last month's report looks great, I am very happy with
                            the progress so far, keep up the good work!</div>
                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src={% static "https://source.unsplash.com/Mv9hjnEUHR4/60x60" %}
                            alt="...">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                            told me that people say this to all dogs, even if they aren't good...</div>
                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                <img class="img-profile rounded-circle"
                    src={% static "img/undraw_profile.svg" %}>
            </a>
            <!-- Dropdown - User Information -->
            
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
            aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Settings
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                Activity Log
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
            </a>
            </div>
        
        </li>

    </ul>

</nav>


<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <form id="logout-form" action="{% url 'gestao_barbearia:logout' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-primary" type="submit">Logout</button>
            </form>
        </div>
    </div>
</div>
</div>

portal_servicos/templates/gestao_barbearia/partials/_scripts.html
{% load static %}

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>