portal_servicos/gestao_barbearia/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'gestao_barbearia'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('funcionario/<int:funcionario_id>/agenda/', views.visualizar_agenda, name='visualizar_agenda'),
    path('barbearia/<int:barbearia_id>/acessar_cliente_app/', views.acessar_cliente_app, name='acessar_cliente_app'),
    path('funcionario/<int:funcionario_id>/agenda/', views.visualizar_agenda, name='visualizar_agenda'),

]

portal_servicos/portal/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

portal_servicos/portal_servicos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls')),
    path('gestao_barbearia/', include('gestao_barbearia.urls')),
    path('cliente_barbearia/', include('cliente_barbearia.urls')),
]

portal_servicos/gestao_barbearia/models.py
from django.db import models
from portal.models import Barbearia, CustomUser


class Funcionario(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    barbearia = models.ForeignKey(Barbearia, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username


class Funcao(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome
    
class Servico(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    duracao = models.DurationField()  # duração do serviço
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    funcao = models.ForeignKey(Funcao, on_delete=models.CASCADE)

    def __str__(self):
        # Converte a duração de timedelta para horas, minutos e segundos
        total_seconds = int(self.duracao.total_seconds())
        hours, remainder = divmod(total_seconds, 3600)
        minutes, seconds = divmod(remainder, 60)
        
        # Formata a duração como HH:MM:SS
        if hours == 0:
            duracao_formatada = f"{minutes:2}min"
        else:
            duracao_formatada = f"{hours:2}h {minutes:2}min"
        
        # Retorna o formato desejado
        return f"{self.nome} - {duracao_formatada}"

 
class Agendamento(models.Model):
    cliente = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='agendamentos')
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE, related_name='agendamentos')
    servico = models.ForeignKey(Servico, on_delete=models.CASCADE, related_name='servicos')
    data_hora = models.DateTimeField()

    class Meta:
        unique_together = ['funcionario', 'data_hora']

    def __str__(self):
        # Formata a data e hora para o formato desejado
        data_hora_formatada = self.data_hora.strftime('%d/%m/%Y %H:%M')
        return f"Cliente {self.cliente.username} - Barbeiro {self.funcionario.user.username} - agendado para {data_hora_formatada}"

    

portal_servicos/gestao_barbearia/forms.py
from django import forms
from portal.models import CustomUser
from .models import Funcionario, Funcao, Agendamento


class FuncionarioForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=CustomUser.objects.filter(is_staff=True))

    class Meta:
        model = Funcionario
        fields = ['user', 'barbearia']
        
class FuncionarioCreationForm(forms.ModelForm):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(required=False)
    funcao = forms.ModelChoiceField(queryset=Funcao.objects.all())

    class Meta:
        model = Funcionario
        fields = ['barbearia', 'funcao']

    def save(self, commit=True):
        user_data = {
            'username': self.cleaned_data['username'],
            'password': self.cleaned_data['password'],
            'first_name': self.cleaned_data.get('first_name', ''),
            'last_name': self.cleaned_data.get('last_name', ''),
            'email': self.cleaned_data.get('email', ''),
        }
        user = CustomUser.objects.create_user(**user_data)
        funcionario = super().save(commit=False)
        funcionario.user = user
        if commit:
            funcionario.save()
        return funcionario


class AgendamentoForm(forms.ModelForm):
    class Meta:
        model = Agendamento
        fields = ['servico', 'data_hora']

    def __init__(self, *args, **kwargs):
        self.funcionario = kwargs.pop('funcionario', None)
        super().__init__(*args, **kwargs)
        if self.funcionario:
            self.fields['servico'].queryset = self.funcionario.barbearia.servicos.all()

    def clean_data_hora(self):
        data_hora = self.cleaned_data['data_hora']
        duracao = self.cleaned_data['servico'].duracao
        conflito = Agendamento.objects.filter(
            funcionario=self.funcionario,
            data_hora__lt=data_hora + duracao,
            data_hora__gte=data_hora
        ).exists()
        if conflito:
            raise forms.ValidationError("Horário indisponível para agendamento.")
        return data_hora

portal_servicos/gestao_barbearia/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from portal.models import Barbearia
from .models import Funcionario, Agendamento, Servico, Funcao
from django.contrib.auth import logout


def logout_view(request):
    logout(request)
    return render(request, 'registration/login.html')

@login_required
def index(request):
    print("aqui 1")
    if request.user.is_owner_app:
        try:
            barbearia = Barbearia.objects.get(owner_app=request.user)
            funcionarios = Funcionario.objects.filter(barbearia=barbearia)
            for funcionario in funcionarios:
                funcoes = Funcao.objects.filter(funcionario=funcionario)
                for funcao in funcoes:
                    funcao.servicos = Servico.objects.filter(funcao=funcao)
                funcionario.funcoes = funcoes
        except Barbearia.DoesNotExist:
            barbearia = None
            funcionarios = []
        return render(request, 'gestao_barbearia/index.html', {'barbearia': barbearia, 'funcionarios': funcionarios, 'funcoes': funcoes})
    else:
        return render(request, 'gestao_barbearia/access_denied.html')


@login_required
def visualizar_agenda(request, funcionario_id):
    funcionario = get_object_or_404(Funcionario, id=funcionario_id)
    return render(request, 'gestao_barbearia/visualizar_agenda.html', {'funcionario': funcionario})

@login_required
def acessar_cliente_app(request, barbearia_id):
    barbearia = get_object_or_404(Barbearia, id=barbearia_id)
    if request.user.is_client_app and request.user.barbearias.filter(id=barbearia.id).exists():
        return redirect('cliente_barbearia:index')
    else:
        return redirect('cliente_barbearia:index')  # Redireciona diretamente para a página do cliente

@login_required
def visualizar_agenda(request, funcionario_id):
    funcionario = get_object_or_404(Funcionario, id=funcionario_id)
    agendamentos = funcionario.agendamentos.all().order_by('data_hora')
    return render(request, 'gestao_barbearia/visualizar_agenda.html', {'funcionario': funcionario, 'agendamentos': agendamentos})

portal_servicos/gestao_barbearia/templates/gestao_barbearia/access_denied.html
<!DOCTYPE html>
<html>
<head>
    <title>Acesso Negado</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1>Acesso Negado</h1>
        <p>Você não tem permissão para acessar esta página.</p>
        <a href="{% url 'home' %}" class="btn btn-primary">Voltar para a Página Inicial</a>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

portal_servicos/gestao_barbearia/templates/gestao_barbearia/index.html
{% extends "gestao_barbearia/base.html" %}

    {% block 'body' %}
        <div class="container mt-5">
            {% if barbearia %}
                <h1 class="mb-4">Bem-vindo à Gestão da Barbearia: {{ barbearia.nome }}</h1>
                <div class="row">
                    <div class="col-md-8">
                        <h2>Informações da Barbearia</h2>
                        <p><strong>Nome:</strong> {{ barbearia.nome }}</p>
                        <p><strong>Tipo de Assinatura:</strong> {{ barbearia.tipo_assinatura }}</p>
                        <p><strong>Assinatura Ativa:</strong> {{ barbearia.assinatura_ativa }}</p>
                        <p><strong>Aberto:</strong> {{ barbearia.aberto }}</p>
                    </div>
                    <div class="col-md-4">
                        <h2>Funcionários</h2>
                        <ul class="list-group">
                            {% for funcionario in funcionarios %}
                                <li class="list-group-item">
                                    <div class="d-flex justify-content-between align-items-center">
                                        {{ funcionario.user.username }} -  
                                            {% for funcao in funcoes %}  {{ funcao.nome }}  - 
                                                {% for servico in funcao.servicos %}  {{ servico.nome }} {% endfor %}
                                            {% endfor %}
                                        <span>
                                            <a href="#" class="btn btn-sm btn-warning">Editar</a>
                                            <a href="#" class="btn btn-sm btn-danger">Remover</a>
                                            <a href="{% url 'gestao_barbearia:visualizar_agenda' funcionario.id %}" class="btn btn-sm btn-info">Visualizar Agenda</a>
                                        </span>
                                    </div>
                                    <ul class="list-group mt-2">
                                        {% for servico in funcionario.servicos %}
                                            <li class="list-group-item">
                                                {{ servico.nome }} - {{ servico.descricao }} - {{ servico.duracao }} - R$ {{ servico.preco }}
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endfor %}
                        </ul>
                        <a href="#" class="btn btn-primary mt-3">Adicionar Funcionário</a>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-md-12">
                        <h2>Acesso ao App Cliente Barbearia</h2>
                        <a href="{% url 'gestao_barbearia:acessar_cliente_app' barbearia.id %}" 
                        class="btn btn-success">Ir para Cliente Barbearia</a>
                    </div>
                </div>
            {% else %}
                <h1 class="mb-4">Bem-vindo à Gestão da Barbearia</h1>
                <p>Você não tem uma barbearia associada.</p>
            {% endif %}
        </div>
    {% endblock %}

portal_servicos/gestao_barbearia/templates/gestao_barbearia/visualizar_agenda.html
<!DOCTYPE html>
<html>
<head>
    <title>Agenda do Funcionário</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1>Agenda de {{ funcionario.user.username }}</h1>
        <ul class="list-group">
            {% for agendamento in agendamentos %}
                <li class="list-group-item">
                    {{ agendamento.data_hora }} - {{ agendamento.cliente.username }} - {{ agendamento.servico.nome }}
                </li>
            {% endfor %}
        </ul>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>